### ISSUE TITLE
Dynamic Pixel ID

### ISSUE THREAD

**Issue by mbagliojr** [NielsKersic/ngx-pixel#1]
I run a SaaS and a customer asked if they could use their pixel in the app. Customers can switch back and forth between businesses so I need to be able to set the pixel id on the "initialize" step. Is this possible?

**Comment by NielsKersic** [comment]
@mbagliojr That's not currently a feature, but I'll work on it this week

**Comment by romperalph** [comment]
Any news about this feature? I think is really important to set the pixel id on the initialize.
Thanks,
