### ISSUE TITLE
Pixel ID with 16 digits

### ISSUE THREAD

**Issue by vicenthy** [NielsKersic/ngx-pixel#3]
the validation rule not permit initialiazy pixel with 16 digits.  how disable this rule?

**Comment by NielsKersic** [comment]
I'm working on a new update for Angular 12 and I'll update this check as well. I'd tried to find documentation about valid Pixel ID's, but I don't think Facebook shares this. For this reason I'll remove the length check altogether. Sorry to hear this caused issues for you.

Planning on getting the new update out in the coming days.
